// Neutral (NOT "use server") module so both Server Actions and API Route
// Handlers can write timeline activity without crossing the Server Action
// trust boundary — importing a "use server" export into a route would turn it
// into a network-invokable action, which this logger must never become.

// @ts-ignore – generated by postinstall / npm run db:generate
import type { Prisma } from "@/generated/prisma/client";
import type { ActivityType } from "@/types";

// Append-only activity feed writer for the Smart Activity Timeline. Takes an
// active Prisma transaction client so the logged event commits atomically with
// the state change that triggered it — a rolled-back mutation logs nothing.
export async function logCaseActivity(
  tx: Prisma.TransactionClient,
  caseId: string,
  type: ActivityType,
  description: string,
  metadata?: Prisma.InputJsonValue,
  userId?: string | null,
) {
  await tx.caseActivity.create({
    data: { caseId, type, description, userId: userId ?? null, metadata: metadata ?? undefined },
  });
}
