import type { CaseDetail } from "@/types";

export const MOCK_CASE_DETAIL: CaseDetail = {
  id: "c1",
  caseNumber: "SC-2024-00341",
  status: "GATHERING_DOCUMENTS",
  caseType: "DISABILITY_PENSION",
  priority: "HIGH",
  claimedPercentage: 65,
  claimDescription:
    "בקשה להגדלת אחוזי נכות עקב החמרה משמעותית בפיברומיאלגיה, כולל שיבוש שינה כרוני, כאבים מפושטים ועייפות קשה המגבילים את כושר העבודה.",
  authorityReferenceNumber: "BL-2024-88741",
  submissionDeadline: "2025-01-15",
  nextFollowUpDate: "2024-12-10",
  lastContactDate: "2024-11-28",
  isOverdue: false,
  hasMissingDocuments: true,
  createdAt: "2024-11-20T10:00:00Z",
  updatedAt: "2024-11-28T09:30:00Z",

  client: {
    id: "cl1",
    fullName: "שרה כהן",
    nationalId: "123456789",
    dateOfBirth: "1975-03-15",
    gender: "FEMALE",
    phone: "052-1234567",
    email: "sarah.cohen@gmail.com",
    addressStreet: "רחוב הרצל 12 דירה 4",
    addressCity: "תל אביב-יפו",
    employmentStatus: "EMPLOYED",
    employer: "חברת אלפא בע\"מ",
    monthlyIncome: 8500,
    spouseIncome: 12000,
    spouseName: "יעקב כהן",
    primaryCondition: "פיברומיאלגיה",
    icdCode: "M79.7",
    recognizedPercentage: 40,
    diagnosisDate: "2020-06-01",
    treatingPhysician: "ד\"ר אריה לוין – ראומטולוג, מרכז רפואי איכילוב",
  },

  assignedAgent: {
    id: "u1",
    name: "מגי לוי",
    email: "magi@smartcase.co.il",
  },

  statusHistory: [
    {
      id: "sh1",
      previousStatus: undefined,
      newStatus: "NEW_INTAKE",
      changedByName: "מנהל מערכת",
      createdAt: "2024-11-20T10:00:00Z",
    },
    {
      id: "sh2",
      previousStatus: "NEW_INTAKE",
      newStatus: "GATHERING_DOCUMENTS",
      changedByName: "מגי לוי",
      reason: "התחלנו לאסוף את המסמכים הנדרשים",
      createdAt: "2024-11-22T08:30:00Z",
    },
  ],

  checklist: [
    {
      id: "ch1",
      documentType: "NATIONAL_ID",
      displayName: "תעודת זהות",
      description: "תעודת זהות ישראלית בתוקף עם ספח",
      isMandatory: true,
      sortOrder: 1,
      status: "APPROVED",
      document: {
        id: "d1",
        fileName: "tz_sarah_cohen.pdf",
        fileSize: 245000,
        issueDate: "2023-05-01",
        isAiReviewed: true,
        aiSummary: "תעודת זהות בתוקף. שם: שרה כהן, ת.ז.: 123456789.",
        aiValidation: {
          isValid: true,
          issues: [],
          recommendations: [],
          summary: "המסמך תקין ומקובל",
        },
        uploadedByName: "מגי לוי",
        createdAt: "2024-11-22T09:00:00Z",
      },
    },
    {
      id: "ch2",
      documentType: "MEDICAL_REPORT",
      displayName: "דו״ח רפואי מרופא מטפל",
      description: "דו״ח מלא מהרופא הראשי על מצב הנכות – לא ישן מ-6 חודשים",
      isMandatory: true,
      validityMonths: 6,
      sortOrder: 2,
      status: "UPLOADED_PENDING_REVIEW",
      document: {
        id: "d2",
        fileName: "medical_report_nov2024.pdf",
        fileSize: 1240000,
        issueDate: "2024-10-15",
        expiryDate: "2025-04-15",
        isAiReviewed: false,
        uploadedByName: "שרה כהן (לקוחה)",
        createdAt: "2024-11-25T14:30:00Z",
      },
    },
    {
      id: "ch3",
      documentType: "PSYCHIATRIC_EVALUATION",
      displayName: "חוות דעת פסיכיאטרית",
      description: "הערכה פסיכיאטרית – נדרשת לתביעות נכות המשפיעות על המצב הנפשי",
      isMandatory: true,
      validityMonths: 6,
      sortOrder: 3,
      status: "REJECTED",
      document: {
        id: "d3",
        fileName: "psychiatric_eval_2023.pdf",
        fileSize: 890000,
        issueDate: "2023-04-20",
        isAiReviewed: true,
        aiSummary: "חוות דעת מ-2023. עברו יותר מ-6 חודשים – המסמך אינו תקין.",
        aiValidation: {
          isValid: false,
          issues: ["המסמך ישן מ-6 חודשים (תאריך הפקה: אפריל 2023)", "נדרש מסמך עדכני מהשנה הנוכחית"],
          recommendations: ["יש לקבל חוות דעת פסיכיאטרית מעודכנת תוך 30 יום"],
          documentAge: "19 חודשים",
          summary: "המסמך פסול – נדרש עדכון",
        },
        reviewNotes: "נדחה – מסמך ישן מ-6 חודשים. יש לעדכן.",
        uploadedByName: "מגי לוי",
        createdAt: "2024-11-23T10:00:00Z",
      },
    },
    {
      id: "ch4",
      documentType: "SALARY_SLIP",
      displayName: "תלושי שכר (3 חודשים אחרונים)",
      description: "תלושי שכר מ-3 החודשים האחרונים עבור שרה וגם עבור בן/בת הזוג",
      isMandatory: true,
      validityMonths: 3,
      sortOrder: 4,
      status: "MISSING",
    },
    {
      id: "ch5",
      documentType: "EMPLOYER_CONFIRMATION",
      displayName: "אישור מעסיק",
      description: "אישור מהמעסיק על תפקיד, מעמד ותנאי עבודה",
      isMandatory: true,
      sortOrder: 5,
      status: "MISSING",
    },
    {
      id: "ch6",
      documentType: "BANK_STATEMENT",
      displayName: "דפי חשבון בנק (3 חודשים)",
      description: "דפי חשבון עו\"ש מהבנק המשפחתי – 3 חודשים אחרונים",
      isMandatory: true,
      validityMonths: 3,
      sortOrder: 6,
      status: "APPROVED",
      document: {
        id: "d6",
        fileName: "bank_oct_nov_dec_2024.pdf",
        fileSize: 520000,
        issueDate: "2024-11-01",
        expiryDate: "2025-02-01",
        isAiReviewed: false,
        uploadedByName: "שרה כהן (לקוחה)",
        createdAt: "2024-11-24T16:00:00Z",
      },
    },
    {
      id: "ch7",
      documentType: "PHOTOGRAPH",
      displayName: "תמונת פנים",
      description: "תמונת פספורט צבעונית – לא ישנה מ-12 חודשים",
      isMandatory: true,
      validityMonths: 12,
      sortOrder: 7,
      status: "UPLOADED_PENDING_REVIEW",
      document: {
        id: "d7",
        fileName: "photo_sarah.jpg",
        fileSize: 180000,
        issueDate: "2024-11-20",
        isAiReviewed: false,
        uploadedByName: "מגי לוי",
        createdAt: "2024-11-22T09:30:00Z",
      },
    },
    {
      id: "ch8",
      documentType: "DISABILITY_CERTIFICATE",
      displayName: "תעודת נכות קיימת",
      description: "תעודת נכות מוכרת קיימת (אם יש)",
      isMandatory: false,
      sortOrder: 8,
      status: "APPROVED",
      document: {
        id: "d8",
        fileName: "disability_cert_40pct.pdf",
        fileSize: 310000,
        issueDate: "2022-01-15",
        isAiReviewed: false,
        uploadedByName: "מגי לוי",
        createdAt: "2024-11-22T09:45:00Z",
      },
    },
  ],

  notes: [
    {
      id: "n1",
      type: "CALL_LOG",
      content:
        "שיחת טלפון עם הלקוחה – הסברתי את תהליך הגשת התביעה. הלקוחה מבינה ומסכימה לשלוח מסמכים. ביקשה הארכה של שבוע לתלושי השכר.",
      followUpDate: "2024-12-10",
      isPrivate: false,
      authorName: "מגי לוי",
      authorInitials: "מל",
      createdAt: "2024-11-28T09:30:00Z",
    },
    {
      id: "n2",
      type: "INTERNAL",
      content:
        "חוות הדעת הפסיכיאטרית נדחתה כי ישנה. שלחתי הנחיות ללקוחה לקבל חוות דעת מעודכנת. יש להקפיד שהמסמך החדש לא יהיה ישן מ-6 חודשים מיום ההגשה.",
      isPrivate: true,
      authorName: "מגי לוי",
      authorInitials: "מל",
      createdAt: "2024-11-23T11:00:00Z",
    },
    {
      id: "n3",
      type: "SYSTEM",
      content: "סטטוס תיק שונה מ\"קליטה חדשה\" ל\"איסוף מסמכים\"",
      isPrivate: false,
      authorName: "מערכת",
      authorInitials: "מ",
      createdAt: "2024-11-22T08:30:00Z",
    },
    {
      id: "n4",
      type: "AUTHORITY_CONTACT",
      content:
        "בירור טלפוני עם נציג ביטוח לאומי בנוגע לדרישות המסמכים עבור תביעת נכות פיברומיאלגיה. אושר שחוות דעת פסיכיאטרית היא חובה ולא אופציונלית לתיק זה.",
      isPrivate: false,
      authorName: "מגי לוי",
      authorInitials: "מל",
      createdAt: "2024-11-21T14:00:00Z",
    },
  ],

  tasks: [
    {
      id: "t1",
      title: "קבלת תלושי שכר מהלקוחה",
      description: "לבקש מהלקוחה תלושי שכר של ספטמבר–נובמבר 2024 עבורה ועבור בעלה",
      dueDate: "2024-12-07",
      priority: "HIGH",
      status: "PENDING",
      assignedToName: "מגי לוי",
      createdAt: "2024-11-28T09:35:00Z",
    },
    {
      id: "t2",
      title: "בדיקת חוות דעת פסיכיאטרית מעודכנת",
      description: "לוודא שהלקוחה קיבלה תור לפסיכיאטר ולעקוב אחר קבלת המסמך",
      dueDate: "2024-12-20",
      priority: "URGENT",
      status: "IN_PROGRESS",
      assignedToName: "מגי לוי",
      createdAt: "2024-11-23T11:30:00Z",
    },
    {
      id: "t3",
      title: "הכנת מכתב בקשה ראשוני",
      description: "להכין טיוטת מכתב בקשה עם נתוני הלקוחה – לאישור לפני שליחה",
      dueDate: "2024-12-15",
      priority: "MEDIUM",
      status: "PENDING",
      assignedToName: "מגי לוי",
      createdAt: "2024-11-22T10:00:00Z",
    },
    {
      id: "t4",
      title: "בדיקת אישור מעסיק",
      description: "להזכיר ללקוחה לבקש אישור מהמעסיק",
      dueDate: "2024-12-05",
      priority: "HIGH",
      status: "PENDING",
      createdAt: "2024-11-28T09:40:00Z",
    },
  ],
};
