import type { ClientListItem } from "@/types";

export const MOCK_CLIENTS: ClientListItem[] = [
  {
    id: "cl1",
    fullName: "שרה כהן",
    nationalId: "123456789",
    dateOfBirth: "1975-03-15",
    gender: "FEMALE",
    phone: "052-1234567",
    email: "sarah.cohen@gmail.com",
    addressCity: "תל אביב-יפו",
    employmentStatus: "EMPLOYED",
    primaryCondition: "פיברומיאלגיה",
    recognizedPercentage: 40,
    isActive: true,
    createdAt: "2024-11-20T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "GATHERING_DOCUMENTS",
    lastCaseType: "DISABILITY_PENSION",
    hasMissingDocuments: true,
    assignedAgentName: "מגי לוי",
    lastActivityDate: "2024-11-28T09:30:00Z",
  },
  {
    id: "cl2",
    fullName: "משה לוי",
    nationalId: "234567891",
    dateOfBirth: "1958-07-22",
    gender: "MALE",
    phone: "054-9876543",
    email: "moshe.levy@walla.co.il",
    addressCity: "ירושלים",
    employmentStatus: "RETIRED",
    primaryCondition: "מחלת פרקינסון",
    recognizedPercentage: 65,
    isActive: true,
    createdAt: "2024-10-15T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 2,
    lastCaseStatus: "GATHERING_DOCUMENTS",
    lastCaseType: "MOBILITY_ALLOWANCE",
    hasMissingDocuments: true,
    assignedAgentName: "דנה ברק",
    lastActivityDate: "2024-11-27T14:00:00Z",
  },
  {
    id: "cl3",
    fullName: "רחל מזרחי",
    nationalId: "345678912",
    dateOfBirth: "1980-12-01",
    gender: "FEMALE",
    phone: "050-1112233",
    email: "rachel.m@hotmail.com",
    addressCity: "חיפה",
    employmentStatus: "UNABLE_TO_WORK",
    primaryCondition: "טרשת נפוצה",
    recognizedPercentage: 50,
    isActive: true,
    createdAt: "2024-09-05T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "PENDING_AI_REVIEW",
    lastCaseType: "GENERAL_DISABILITY_ALLOWANCE",
    hasMissingDocuments: false,
    assignedAgentName: "מגי לוי",
    lastActivityDate: "2024-11-25T11:00:00Z",
  },
  {
    id: "cl4",
    fullName: "יוסף אברהם",
    nationalId: "456789123",
    dateOfBirth: "1965-05-08",
    gender: "MALE",
    phone: "053-4445566",
    addressCity: "ראשון לציון",
    employmentStatus: "SELF_EMPLOYED",
    primaryCondition: "כאבי גב כרוניים – דיסק L4-L5",
    recognizedPercentage: 30,
    isActive: true,
    createdAt: "2024-08-01T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "READY_FOR_SUBMISSION",
    lastCaseType: "DISABILITY_PENSION",
    hasMissingDocuments: false,
    assignedAgentName: "רון שמיר",
    lastActivityDate: "2024-11-26T16:00:00Z",
  },
  {
    id: "cl5",
    fullName: "מרים פרידמן",
    nationalId: "567891234",
    dateOfBirth: "1971-09-30",
    gender: "FEMALE",
    phone: "058-7778899",
    email: "miriam.f@gmail.com",
    addressCity: "בני ברק",
    employmentStatus: "UNEMPLOYED",
    primaryCondition: "דיכאון קשה ו-PTSD",
    recognizedPercentage: 35,
    isActive: true,
    createdAt: "2024-07-20T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "SUBMITTED",
    lastCaseType: "INCOME_SUPPORT",
    hasMissingDocuments: false,
    assignedAgentName: "דנה ברק",
    lastActivityDate: "2024-11-10T10:00:00Z",
  },
  {
    id: "cl6",
    fullName: "דוד כץ",
    nationalId: "678912345",
    dateOfBirth: "1969-02-14",
    gender: "MALE",
    phone: "052-3334455",
    email: "david.katz@outlook.com",
    addressCity: "אשדוד",
    employmentStatus: "EMPLOYED",
    primaryCondition: "פגיעת ברך בתאונת עבודה",
    recognizedPercentage: 25,
    isActive: true,
    createdAt: "2024-06-10T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "AWAITING_DECISION",
    lastCaseType: "WORK_ACCIDENT",
    hasMissingDocuments: false,
    assignedAgentName: "רון שמיר",
    lastActivityDate: "2024-11-01T09:00:00Z",
  },
  {
    id: "cl7",
    fullName: "אורית שוחט",
    nationalId: "789123456",
    dateOfBirth: "1955-11-25",
    gender: "FEMALE",
    phone: "054-6667788",
    addressCity: "נתניה",
    employmentStatus: "RETIRED",
    primaryCondition: "ראומטואיד ארתריטיס",
    recognizedPercentage: 70,
    isActive: true,
    createdAt: "2024-05-01T10:00:00Z",
    activeCasesCount: 0,
    totalCasesCount: 1,
    lastCaseStatus: "APPROVED",
    lastCaseType: "DISABILITY_PENSION",
    hasMissingDocuments: false,
    assignedAgentName: "מגי לוי",
    lastActivityDate: "2024-11-15T12:00:00Z",
  },
  {
    id: "cl8",
    fullName: "ניר בן-דוד",
    nationalId: "891234567",
    dateOfBirth: "1983-04-17",
    gender: "MALE",
    phone: "050-9990011",
    email: "nir.bendavid@gmail.com",
    addressCity: "פתח תקווה",
    employmentStatus: "EMPLOYED",
    primaryCondition: "אפילפסיה מפושטת",
    recognizedPercentage: 20,
    isActive: true,
    createdAt: "2024-04-10T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "REJECTED",
    lastCaseType: "GENERAL_DISABILITY_ALLOWANCE",
    hasMissingDocuments: false,
    assignedAgentName: "דנה ברק",
    lastActivityDate: "2024-11-20T08:00:00Z",
  },
  {
    id: "cl9",
    fullName: "ספיר גל",
    nationalId: "912345678",
    dateOfBirth: "1990-08-03",
    gender: "FEMALE",
    phone: "053-2223344",
    email: "sapir.gal@walla.co.il",
    addressCity: "רחובות",
    employmentStatus: "STUDENT",
    primaryCondition: "לופוס (SLE) – מחלה אוטואימונית",
    recognizedPercentage: 45,
    isActive: true,
    createdAt: "2024-03-01T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 2,
    lastCaseStatus: "APPEAL_IN_PROGRESS",
    lastCaseType: "APPEAL",
    hasMissingDocuments: true,
    assignedAgentName: "רון שמיר",
    lastActivityDate: "2024-11-28T07:00:00Z",
  },
  {
    id: "cl10",
    fullName: "עמית רוזן",
    nationalId: "102345678",
    dateOfBirth: "1977-01-19",
    gender: "MALE",
    phone: "058-5556677",
    addressCity: "בת ים",
    employmentStatus: "EMPLOYED",
    primaryCondition: "ניוון שרירים מתקדם",
    recognizedPercentage: 60,
    isActive: true,
    createdAt: "2024-11-27T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "NEW_INTAKE",
    lastCaseType: "MOBILITY_ALLOWANCE",
    hasMissingDocuments: true,
    assignedAgentName: undefined,
    lastActivityDate: "2024-11-27T10:00:00Z",
  },
  {
    id: "cl11",
    fullName: "חנה שפירא",
    nationalId: "112345679",
    dateOfBirth: "1948-06-12",
    gender: "FEMALE",
    phone: "052-8889900",
    email: "hana.s@bezeqint.net",
    addressCity: "ירושלים",
    employmentStatus: "RETIRED",
    primaryCondition: "שבץ מוחי עם פגיעה מוטורית",
    recognizedPercentage: 75,
    isActive: true,
    createdAt: "2024-11-10T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "GATHERING_DOCUMENTS",
    lastCaseType: "LONG_TERM_CARE",
    hasMissingDocuments: true,
    assignedAgentName: "מגי לוי",
    lastActivityDate: "2024-11-26T10:00:00Z",
  },
  {
    id: "cl12",
    fullName: "אלון אדרי",
    nationalId: "122345670",
    dateOfBirth: "1986-10-28",
    gender: "MALE",
    phone: "050-4445556",
    email: "alon.adri@gmail.com",
    addressCity: "תל אביב-יפו",
    employmentStatus: "SELF_EMPLOYED",
    primaryCondition: "סוכרת סוג 1 עם סיבוכים",
    recognizedPercentage: 30,
    isActive: true,
    createdAt: "2024-07-08T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "SUBMITTED",
    lastCaseType: "DISABILITY_PENSION",
    hasMissingDocuments: false,
    assignedAgentName: "דנה ברק",
    lastActivityDate: "2024-11-05T10:00:00Z",
  },
  {
    id: "cl13",
    fullName: "יעל גורן",
    nationalId: "132345671",
    dateOfBirth: "1972-03-05",
    gender: "FEMALE",
    phone: "054-1112223",
    addressCity: "חיפה",
    employmentStatus: "UNABLE_TO_WORK",
    primaryCondition: "פגיעת שמע מקצועית (טינטון)",
    recognizedPercentage: 20,
    isActive: true,
    createdAt: "2024-08-15T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "AWAITING_DECISION",
    lastCaseType: "OCCUPATIONAL_DISEASE",
    hasMissingDocuments: false,
    assignedAgentName: "רון שמיר",
    lastActivityDate: "2024-10-30T11:00:00Z",
  },
  {
    id: "cl14",
    fullName: "שלמה ברג",
    nationalId: "142345672",
    dateOfBirth: "1952-08-18",
    gender: "MALE",
    phone: "053-6667779",
    email: "shlomo.berg@walla.co.il",
    addressCity: "נתניה",
    employmentStatus: "RETIRED",
    primaryCondition: "אלצהיימר מוקדם – שלב ראשוני",
    recognizedPercentage: 55,
    isActive: true,
    createdAt: "2024-09-20T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "GATHERING_DOCUMENTS",
    lastCaseType: "LONG_TERM_CARE",
    hasMissingDocuments: true,
    assignedAgentName: "דנה ברק",
    lastActivityDate: "2024-11-22T13:00:00Z",
  },
  {
    id: "cl15",
    fullName: "נועה אלמוג",
    nationalId: "152345673",
    dateOfBirth: "1995-12-30",
    gender: "FEMALE",
    phone: "058-3334445",
    email: "noa.almog@gmail.com",
    addressCity: "ראשון לציון",
    employmentStatus: "EMPLOYED",
    primaryCondition: "הפרעת ספקטרום אוטיסטית (ASD) – תפקוד גבוה",
    recognizedPercentage: 40,
    isActive: true,
    createdAt: "2024-10-01T10:00:00Z",
    activeCasesCount: 1,
    totalCasesCount: 1,
    lastCaseStatus: "NEW_INTAKE",
    lastCaseType: "DISABILITY_PENSION",
    hasMissingDocuments: true,
    assignedAgentName: undefined,
    lastActivityDate: "2024-10-01T10:00:00Z",
  },
];

export const MOCK_CITIES = [...new Set(MOCK_CLIENTS.map((c) => c.addressCity).filter(Boolean))] as string[];
