// In Prisma 7 the connection URL is no longer read from schema.prisma at runtime.
// The driver adapter owns the connection: it reads DATABASE_URL and creates the pg pool.
//
// @ts-ignore – generated by `npm run db:generate` (postinstall on Vercel, manual locally)
import { PrismaClient } from "@/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

function createPrismaClient(): PrismaClient {
  const adapter = new PrismaPg(process.env.DATABASE_URL!);
  // @ts-ignore – constructor accepts adapter in Prisma 7
  return new PrismaClient({
    adapter,
    log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });
}

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma: PrismaClient =
  globalForPrisma.prisma ?? createPrismaClient();

// Reuse one instance across hot-reloads in dev; production creates fresh per cold-start.
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
