// The Prisma client is generated into src/generated/prisma by the `postinstall`
// script (`prisma generate`). On Vercel this runs automatically after `npm install`.
// Locally: run `npm install` once, or `npm run db:generate` after setting DATABASE_URL.
//
// The @ts-ignore below is intentional: the import is always valid at runtime
// (postinstall ensures the module exists before any compilation step runs).
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore – generated by postinstall / npm run db:generate
import { PrismaClient } from "@/generated/prisma";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma: PrismaClient =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });

// Reuse one instance across hot-reloads in development.
// In production each Vercel serverless invocation may spin up a new instance — that is expected.
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
