// Command executors for the Telegram ingress — the side-effecting half.
//
// Every pure decision (auth, parsing, formatting) lives in guards.ts /
// responses.ts and is unit tested there. This file only wires those to the
// process and the database.

import { execFile } from "node:child_process";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { PrismaPg } from "@prisma/adapter-pg";

// @ts-ignore – generated by npm run db:generate
import { PrismaClient } from "../../src/generated/prisma/client";
import { CASE_STATUS_LABELS, CASE_TYPE_LABELS } from "../../src/lib/constants";
import { generateText } from "../../src/lib/plugins/ai";
import { extractCaseReference, type KnownCommand } from "./guards";
import {
  formatError,
  formatStatus,
  formatTestResult,
  parseTestSummary,
  truncateForTelegram,
  HELP_TEXT,
} from "./responses";

const execFileAsync = promisify(execFile);
const REPO_ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

/** A test run can legitimately take minutes; anything past this is a hang. */
const TEST_TIMEOUT_MS = 10 * 60 * 1000;

let prismaSingleton: PrismaClient | null = null;

/**
 * Lazy Prisma client. Built here rather than imported from src/lib/prisma.ts
 * because that module is Next-runtime shaped; scripts construct their own
 * adapter (same pattern as scripts/case-audit.ts).
 */
function getPrisma(): PrismaClient {
  if (!prismaSingleton) {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) throw new Error("DATABASE_URL is not set");
    prismaSingleton = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
  }
  return prismaSingleton;
}

export async function disconnectPrisma(): Promise<void> {
  if (prismaSingleton) {
    await prismaSingleton.$disconnect();
    prismaSingleton = null;
  }
}

async function git(args: string[]): Promise<string> {
  const { stdout } = await execFileAsync("git", args, { cwd: REPO_ROOT });
  return stdout.trim();
}

export async function handleStatus(): Promise<string> {
  try {
    const [branch, lastCommit, porcelain] = await Promise.all([
      git(["rev-parse", "--abbrev-ref", "HEAD"]),
      git(["log", "-1", "--pretty=%h %s"]),
      git(["status", "--porcelain"]),
    ]);
    const dirtyFiles = porcelain ? porcelain.split("\n").filter(Boolean).length : 0;
    return formatStatus({ branch, lastCommit, dirtyFiles });
  } catch (error) {
    return formatError("שליפת סטטוס הריפו נכשלה", error);
  }
}

/**
 * Run the suite and report the counters.
 *
 * `npm test` exits non-zero on failure, which rejects execFile — so the summary
 * is parsed from the error's captured stdout too, not only the success path.
 * A failing suite is a normal, reportable outcome here, not an exception.
 */
export async function handleRunTests(): Promise<string> {
  let stdout = "";
  let stderr = "";
  let exitCode = 0;

  try {
    const result = await execFileAsync("npm", ["test"], {
      cwd: REPO_ROOT,
      timeout: TEST_TIMEOUT_MS,
      maxBuffer: 20 * 1024 * 1024,
    });
    stdout = result.stdout;
    stderr = result.stderr;
  } catch (error) {
    const err = error as { stdout?: string; stderr?: string; code?: number };
    stdout = err.stdout ?? "";
    stderr = err.stderr ?? "";
    exitCode = typeof err.code === "number" ? err.code : 1;
  }

  const combined = `${stdout}\n${stderr}`;
  const summary = parseTestSummary(combined);
  const tail = combined.split("\n").filter(Boolean).slice(-15).join("\n");
  return formatTestResult(summary, exitCode, tail);
}

const SYSTEM_PROMPT = [
  "אתה עוזר פנימי של משרד SmartCase, עונה לצוות המשרד בטלגרם.",
  "ענה בעברית, בקצרה ובאופן מעשי, בטקסט רגיל בלבד ללא Markdown.",
  "השתמש אך ורק בנתונים שסופקו לך בהקשר. אם המידע חסר — אמור שאינך יודע.",
  "אין באפשרותך לשנות נתונים; הגישה שלך היא לקריאה בלבד.",
].join("\n");

/**
 * Read-only case context for the AI path.
 *
 * `select` is explicit and narrow — this is the trust boundary for what a
 * Telegram message can pull out of a legal/medical record, so it is a
 * whitelist, never a full-row fetch. Nothing here writes.
 */
async function loadCaseContext(reference: string): Promise<string | null> {
  const prisma = getPrisma();

  const where = /^SC-\d{4}-\d{5}$/i.test(reference)
    ? { caseNumber: reference.toUpperCase() }
    : /^\d+$/.test(reference)
      ? { caseNumber: `SC-${new Date().getFullYear()}-${reference.padStart(5, "0")}` }
      : { id: reference };

  const record = await prisma.case.findUnique({
    where,
    select: {
      caseNumber: true,
      caseType: true,
      status: true,
      priority: true,
      submissionDeadline: true,
      nextFollowUpDate: true,
      hasMissingDocuments: true,
      isOverdue: true,
      updatedAt: true,
      client: { select: { fullName: true } },
      tasks: {
        where: { status: { in: ["PENDING", "IN_PROGRESS"] } },
        select: { title: true, dueDate: true },
        take: 10,
      },
      documents: { select: { status: true, documentType: true }, take: 30 },
    },
  });
  if (!record) return null;

  const missing = record.documents.filter((doc: { status: string }) => doc.status !== "APPROVED").length;
  const openTasks = record.tasks
    .map((task: { title: string }) => `- ${task.title}`)
    .join("\n");

  return [
    `מספר תיק: ${record.caseNumber}`,
    `לקוח: ${record.client.fullName}`,
    `סוג: ${CASE_TYPE_LABELS[record.caseType as keyof typeof CASE_TYPE_LABELS] ?? record.caseType}`,
    `סטטוס: ${CASE_STATUS_LABELS[record.status as keyof typeof CASE_STATUS_LABELS] ?? record.status}`,
    `עדיפות: ${record.priority}`,
    `מסמכים שאינם מאושרים: ${missing} מתוך ${record.documents.length}`,
    `חורג מיעד: ${record.isOverdue ? "כן" : "לא"}`,
    record.submissionDeadline ? `תאריך יעד להגשה: ${record.submissionDeadline.toISOString().slice(0, 10)}` : null,
    record.nextFollowUpDate ? `מעקב הבא: ${record.nextFollowUpDate.toISOString().slice(0, 10)}` : null,
    openTasks ? `משימות פתוחות:\n${openTasks}` : "משימות פתוחות: אין",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Natural-language path: resolve any referenced case read-only, then let the
 * configured AI provider answer over that context.
 */
export async function handleNaturalLanguage(text: string): Promise<string> {
  try {
    const reference = extractCaseReference(text);
    let context = "לא צוין תיק ספציפי.";

    if (reference) {
      const loaded = await loadCaseContext(reference);
      if (!loaded) return `לא נמצא תיק עבור "${reference}".`;
      context = loaded;
    }

    const result = await generateText({
      prompt: `הקשר התיק:\n${context}\n\nבקשת המשתמש:\n${text}`,
      systemPrompt: SYSTEM_PROMPT,
      maxTokens: 800,
      temperature: 0.2,
    });

    return truncateForTelegram(result.text.trim());
  } catch (error) {
    return formatError("עיבוד הבקשה נכשל", error);
  }
}

/** No current command takes arguments; add a parameter when one does. */
export async function runCommand(name: KnownCommand): Promise<string> {
  switch (name) {
    case "help":
      return HELP_TEXT;
    case "status":
      return handleStatus();
    case "run-tests":
      return handleRunTests();
  }
}
