// Edge-safe auth config — no Node.js-only imports (Prisma, bcrypt, etc.).
// Imported by middleware.ts (Edge runtime) and extended by auth.ts (Node.js).
import type { NextAuthConfig } from "next-auth"
// @ts-ignore – generated by postinstall / npm run db:generate (type-only, erased at build)
import type { UserRole, UserStatus } from "@/generated/prisma/client"

export const authConfig = {
  // Trust the deployment host header. Required for `next start` and proxied
  // deployments (Vercel sets this automatically, self-hosted does not).
  trustHost: true,

  pages: {
    signIn: "/login",
    // Keep OAuth/auth errors (e.g. Google AccessDenied) on our branded login
    // page — ?error= is read there — instead of Auth.js's default /api/auth/error.
    error: "/login",
  },

  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user
      const path = nextUrl.pathname

      // Admin-only surface: authenticate first, then gate on role. This is
      // defense-in-depth — the real role check also lives in the /admin server
      // layout and in every admin server action (never trust the edge alone).
      if (path.startsWith("/admin")) {
        if (!isLoggedIn) return false
        if (auth!.user!.role !== "ADMIN") return Response.redirect(new URL("/dashboard", nextUrl))
        return true
      }

      const isProtected =
        path.startsWith("/dashboard") ||
        path.startsWith("/cases") ||
        path.startsWith("/clients") ||
        path.startsWith("/scheduling") ||
        path.startsWith("/tasks") ||
        path.startsWith("/documents") ||
        path.startsWith("/ai-tools") ||
        path.startsWith("/settings")

      const isAuthPage = path === "/login" || path === "/register"

      if (isProtected) {
        // Unauthenticated → NextAuth redirects to pages.signIn automatically
        return isLoggedIn
      }

      if (isAuthPage && isLoggedIn) {
        // Already logged in and hitting /login or /register → back to dashboard
        return Response.redirect(new URL("/dashboard", nextUrl))
      }

      return true
    },

    // Edge-safe session mapping (no DB). Projects the JWT claims — written by
    // the Node `jwt` callback in auth.ts — onto the session so the Edge
    // middleware's `authorized` check above can read `role`. The Node instance
    // overrides this with its own richer session callback.
    session({ session, token }) {
      if (session.user) {
        session.user.id     = token.id     as string
        session.user.role   = token.role   as UserRole
        session.user.status = token.status as UserStatus
      }
      return session
    },
  },

  providers: [],
} satisfies NextAuthConfig
