// Full NextAuth config — Node.js only (imports Prisma + bcryptjs).
// Do NOT import this file from middleware.ts; use auth.config.ts there instead.
import NextAuth, { CredentialsSignin } from "next-auth"
import Credentials from "next-auth/providers/credentials"
import Google from "next-auth/providers/google"
// @ts-ignore – generated by postinstall / npm run db:generate
import type { UserRole, UserStatus } from "@/generated/prisma/client"
import { prisma } from "@/lib/prisma"
import { verifyCredentials } from "@/lib/services/credentials"
import { authConfig } from "./auth.config"

// How long a JWT may trust its cached `status` before we re-check the DB.
// Bounds the window in which a just-suspended user keeps a live session.
const STATUS_RECHECK_MS = 5 * 60 * 1000

// Distinguishable credential errors. NextAuth surfaces `.code` to the client
// (login page maps it → Hebrew copy); the generic error type stays
// "CredentialsSignin" so a wrong password and a blocked account are not
// externally distinguishable without valid credentials.
class PendingApprovalError extends CredentialsSignin {
  code = "pending_approval"
}
class AccountSuspendedError extends CredentialsSignin {
  code = "suspended"
}

export const { auth, handlers, signIn, signOut } = NextAuth({
  ...authConfig,

  session: { strategy: "jwt" },

  providers: [
    Credentials({
      credentials: {
        email:    { label: "Email",    type: "email"    },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        const email    = credentials?.email    as string | undefined
        const password = credentials?.password as string | undefined
        if (!email || !password) return null

        // Shared with POST /api/auth/login — password is validated BEFORE
        // account state is revealed (see src/lib/services/credentials.ts).
        const outcome = await verifyCredentials(email, password)
        if (!outcome.ok) {
          if (outcome.reason === "pending_approval") throw new PendingApprovalError()
          if (outcome.reason === "suspended")        throw new AccountSuspendedError()
          return null
        }
        return outcome.user
      },
    }),

    // Google is linking-only: it authenticates the person, but authorization
    // still comes exclusively from an existing APPROVED staff account whose
    // email matches (gated in the signIn callback). No account is auto-created
    // via Google — the admin-approval gate is the only way in.
    Google({
      clientId:     process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],

  callbacks: {
    authorized: authConfig.callbacks?.authorized,

    // Runs before jwt(). For Google we enforce the linking-only model here:
    // require a Google-verified email that maps to an existing APPROVED user.
    // Returning false → generic AccessDenied (no distinction between "unknown
    // email" and "not approved"), preserving the enumeration protection the
    // Credentials path already has.
    async signIn({ user, account, profile }) {
      if (account?.provider !== "google") return true // Credentials: gated in authorize()

      if (!(profile as { email_verified?: boolean } | undefined)?.email_verified) return false
      if (!user.email) return false

      // Sole Google gate: resolve the staff account by a case-insensitive email
      // match and require APPROVED. Seed the DB id/role/status onto `user` so
      // jwt() reuses them with no second DB round-trip — with the JWT strategy
      // (no adapter) the same `user` object flows straight into jwt() on initial
      // sign-in. `user.id` here is Google's `sub`; overwrite it with our id so
      // the throttled re-check in jwt() keys off the DB id like the creds path.
      const dbUser = await prisma.user.findFirst({
        where: { email: { equals: user.email, mode: "insensitive" } },
        select: { id: true, role: true, status: true },
      })
      if (dbUser?.status !== "APPROVED") return false

      user.id = dbUser.id
      ;(user as { role?: UserRole }).role     = dbUser.role
      ;(user as { status?: UserStatus }).status = dbUser.status
      return true
    },

    async jwt({ token, user }) {
      // Initial sign-in: seed claims from the authorized user. Credentials: from
      // authorize()'s return. Google: signIn() has already resolved and attached
      // the DB id/role/status onto this same object — no provider branch needed.
      if (user) {
        token.id     = user.id as string
        token.role   = (user as { role: UserRole }).role
        token.status = (user as { status: UserStatus }).status
        token.statusCheckedAt = Date.now()
        return token
      }

      // Subsequent requests: throttled DB re-check so an admin suspending a user
      // (or changing their role) takes effect within STATUS_RECHECK_MS on live
      // sessions instead of only at next login.
      const checkedAt = token.statusCheckedAt as number | undefined
      if (!checkedAt || Date.now() - checkedAt > STATUS_RECHECK_MS) {
        const fresh = await prisma.user.findUnique({
          where: { id: token.id as string },
          select: { role: true, status: true },
        })
        // Deleted or no-longer-approved → returning null destroys the session.
        if (!fresh || fresh.status !== "APPROVED") return null
        token.role   = fresh.role
        token.status = fresh.status
        token.statusCheckedAt = Date.now()
      }

      return token
    },

    session({ session, token }) {
      if (session.user) {
        session.user.id     = token.id     as string
        session.user.role   = token.role   as UserRole
        session.user.status = token.status as UserStatus
      }
      return session
    },
  },
})
