// Full NextAuth config — Node.js only (imports Prisma + bcryptjs).
// Do NOT import this file from middleware.ts; use auth.config.ts there instead.
import NextAuth, { CredentialsSignin } from "next-auth"
import Credentials from "next-auth/providers/credentials"
import bcrypt from "bcryptjs"
// @ts-ignore – generated by postinstall / npm run db:generate
import type { UserRole, UserStatus } from "@/generated/prisma/client"
import { prisma } from "@/lib/prisma"
import { authConfig } from "./auth.config"

// How long a JWT may trust its cached `status` before we re-check the DB.
// Bounds the window in which a just-suspended user keeps a live session.
const STATUS_RECHECK_MS = 5 * 60 * 1000

// Distinguishable credential errors. NextAuth surfaces `.code` to the client
// (login page maps it → Hebrew copy); the generic error type stays
// "CredentialsSignin" so a wrong password and a blocked account are not
// externally distinguishable without valid credentials.
class PendingApprovalError extends CredentialsSignin {
  code = "pending_approval"
}
class AccountSuspendedError extends CredentialsSignin {
  code = "suspended"
}

export const { auth, handlers, signIn, signOut } = NextAuth({
  ...authConfig,

  session: { strategy: "jwt" },

  providers: [
    Credentials({
      credentials: {
        email:    { label: "Email",    type: "email"    },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        const email    = credentials?.email    as string | undefined
        const password = credentials?.password as string | undefined
        if (!email || !password) return null

        const user = await prisma.user.findUnique({
          where: { email },
          select: { id: true, name: true, email: true, passwordHash: true, role: true, status: true },
        })

        if (!user) return null

        // Validate the password BEFORE revealing account state — never leak
        // "pending"/"suspended" to someone who can't authenticate (enumeration).
        const valid = await bcrypt.compare(password, user.passwordHash)
        if (!valid) return null

        if (user.status === "PENDING_APPROVAL") throw new PendingApprovalError()
        if (user.status === "SUSPENDED")        throw new AccountSuspendedError()

        return { id: user.id, name: user.name, email: user.email, role: user.role, status: user.status }
      },
    }),
  ],

  callbacks: {
    authorized: authConfig.callbacks?.authorized,

    async jwt({ token, user }) {
      // Initial sign-in: seed claims from the authorized user.
      if (user) {
        token.id     = user.id
        token.role   = (user as { role: UserRole }).role
        token.status = (user as { status: UserStatus }).status
        token.statusCheckedAt = Date.now()
        return token
      }

      // Subsequent requests: throttled DB re-check so an admin suspending a user
      // (or changing their role) takes effect within STATUS_RECHECK_MS on live
      // sessions instead of only at next login.
      const checkedAt = token.statusCheckedAt as number | undefined
      if (!checkedAt || Date.now() - checkedAt > STATUS_RECHECK_MS) {
        const fresh = await prisma.user.findUnique({
          where: { id: token.id as string },
          select: { role: true, status: true },
        })
        // Deleted or no-longer-approved → returning null destroys the session.
        if (!fresh || fresh.status !== "APPROVED") return null
        token.role   = fresh.role
        token.status = fresh.status
        token.statusCheckedAt = Date.now()
      }

      return token
    },

    session({ session, token }) {
      if (session.user) {
        session.user.id     = token.id     as string
        session.user.role   = token.role   as UserRole
        session.user.status = token.status as UserStatus
      }
      return session
    },
  },
})
