import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { auth } from "@/../auth";
import { prisma } from "@/lib/prisma";
// @ts-ignore – generated by postinstall / npm run db:generate
import type { Prisma } from "@/generated/prisma/client";
import { logCaseActivity } from "@/lib/activity";
import { getGeminiClient } from "@/lib/ai/gemini";
import { staleClaimCutoff } from "@/lib/ai/transcription";
import {
  STORY_INTAKE_MAX_OUTPUT_TOKENS,
  STORY_INTAKE_MODEL,
  buildStoryIntakePrompt,
  parseStoryIntake,
} from "@/lib/ai/story-intake-schema";
import {
  INTAKE_MANAGER_TASK_TITLE,
  runStoryIntake,
  type StoryIntakePorts,
} from "@/lib/workflows/story-intake";

// Intake extractor: turns one COMPLETED personal-story transcript into a
// structured intake and fans it out into case side effects.
//
// The transcript is long and the Gemini call is the whole 60s budget, so this
// route deliberately processes exactly ONE profile per invocation rather than a
// batch (unlike the transcription worker it sits downstream of).

// Same two ways in as /api/ai/transcribe: a staff session, or the Vercel Cron
// bearer. If CRON_SECRET is unset the bearer branch is disabled entirely rather
// than defaulting open.
// Returns the acting user id as well, because every write below needs an actor
// and resolving the session twice would just be a second DB-backed JWT decode.
async function authorize(req: Request): Promise<{ ok: boolean; userId?: string }> {
  const secret = process.env.CRON_SECRET;
  if (secret && req.headers.get("authorization") === `Bearer ${secret}`) return { ok: true };
  const session = await auth();
  return session?.user ? { ok: true, userId: session.user.id } : { ok: false };
}

// "Never extracted" is null, so the claimable set is null ∪ {PENDING, FAILED}.
// FAILED is retryable — the usual causes (a truncated Gemini response, a
// transient 5xx) are transient. Written once and reused by the claim so the
// queue predicate and the claim predicate cannot drift.
const CLAIMABLE = {
  OR: [{ intakeStatus: null }, { intakeStatus: { in: ["PENDING", "FAILED"] } }],
} satisfies Prisma.ConversionProfileWhereInput;

// Task.createdById is required and the cron path has no session user, so the
// actor falls back to the case's assigned agent and then to its creator.
// Resolved lazily inside the ports so a run with no writes never pays for it.
async function resolveActorId(caseId: string, sessionUserId?: string): Promise<string> {
  if (sessionUserId) return sessionUserId;
  const c = await prisma.case.findUniqueOrThrow({
    where: { id: caseId },
    select: { assignedAgentId: true, createdById: true },
  });
  return c.assignedAgentId ?? c.createdById;
}

// Real ports: Prisma for every write, nothing else. Each port is the whole
// business outcome for its branch — in particular flagForManager commits the
// priority bump, the manager task and the timeline entry in ONE transaction,
// because a case silently raised to URGENT with no task and no trace is worse
// than no escalation at all.
const buildPorts = (sessionUserId?: string): StoryIntakePorts => ({
  listOpenTaskTitles: async (caseId) => {
    const rows = await prisma.task.findMany({
      where: { caseId, status: { in: ["PENDING", "IN_PROGRESS"] } },
      select: { title: true },
    });
    return rows.map((r) => r.title);
  },

  createTasks: async (caseId, tasks) => {
    const actorId = await resolveActorId(caseId, sessionUserId);
    const created = await prisma.task.createMany({
      data: tasks.map((t) => ({
        caseId,
        createdById: actorId,
        title: t.title,
        description: t.description,
        dueDate: t.dueDate,
        priority: "HIGH" as const,
      })),
    });
    return created.count;
  },

  flagForManager: async (caseId, notes) => {
    const actorId = await resolveActorId(caseId, sessionUserId);
    await prisma.$transaction(async (tx) => {
      await tx.case.update({ where: { id: caseId }, data: { priority: "URGENT" } });
      // Fixed title, so a re-run finds the escalation it already opened instead
      // of stacking a second urgent task on the same finding.
      const existing = await tx.task.findFirst({
        where: { caseId, title: INTAKE_MANAGER_TASK_TITLE, status: { in: ["PENDING", "IN_PROGRESS"] } },
        select: { id: true },
      });
      if (!existing) {
        await tx.task.create({
          data: {
            caseId,
            createdById: actorId,
            title: INTAKE_MANAGER_TASK_TITLE,
            description: notes ?? "ה-AI סימן ממצאים חריגים בסיפור האישי, ללא פירוט.",
            priority: "URGENT",
          },
        });
      }
      await logCaseActivity(
        tx,
        caseId,
        "AI_CALL_SUMMARY",
        "ניתוח הסיפור האישי סימן ממצאים החורגים מהרגיל — התיק הועלה לעדיפות דחופה.",
        { redFlags: true },
        sessionUserId ?? null,
      );
    });
  },

  saveIntake: async (caseId, intake, at) => {
    await prisma.$transaction(async (tx) => {
      await tx.conversionProfile.update({
        where: { caseId },
        data: { intake, intakeStatus: "COMPLETED", intakeAt: at },
      });
      // Metadata carries ids and flags only — never transcript or story text.
      await logCaseActivity(
        tx,
        caseId,
        "AI_CALL_SUMMARY",
        "הופק אינטייק מובנה מתמלול הסיפור האישי.",
        { gaps: intake.gaps, redFlags: intake.hasRedFlags },
        sessionUserId ?? null,
      );
    });
  },

  logError: (message, err) => console.error(message, err),
});

// Optional targeting for the manual staff trigger. The cron path sends no body.
const targetSchema = z.object({ caseId: z.string().min(1) }).partial();

// Best-effort release of a run we cannot call finished. A row left in
// PROCESSING is invisible to every later run, so failing to move it is the one
// outcome worth swallowing an error over. Deliberately NOT scoped to
// intakeStatus: PROCESSING — the save branch may already have latched the row
// to COMPLETED while a sibling branch failed, and COMPLETED is exactly the
// state that would make the miss permanent. Only the invocation holding the
// claim ever calls this, so there is no concurrent COMPLETED to clobber.
async function releaseClaim(profileId: string) {
  await prisma.conversionProfile
    .updateMany({ where: { id: profileId }, data: { intakeStatus: "FAILED" } })
    .catch((err) => console.error("[ai/story-intake] claim release failed", err));
}

// Rows stranded in PROCESSING by an invocation that died mid-flight (a Gemini
// call that ran past the 60s budget, a crashed instance) — the catch below
// never got to run, and PROCESSING is outside CLAIMABLE, so nothing would ever
// pick them up again. Same sweep the transcription worker runs, on the same
// timeout: updatedAt is the claim timestamp, because the claim is the write
// that last touched the row.
async function resetStaleClaims(now: Date) {
  await prisma.conversionProfile
    .updateMany({
      where: { intakeStatus: "PROCESSING", updatedAt: { lt: staleClaimCutoff(now) } },
      data: { intakeStatus: "FAILED" },
    })
    .catch((err) => console.error("[ai/story-intake] stale-claim sweep failed", err));
}

async function handle(req: Request) {
  const actor = await authorize(req);
  if (!actor.ok) return NextResponse.json({ error: "לא מורשה" }, { status: 401 });
  const sessionUserId = actor.userId;

  // GET (cron) has no body and runs the untargeted queue. A POST body that
  // fails validation must NOT degrade into that global scan: it would silently
  // extract, open tasks on and possibly escalate the oldest OTHER case in the
  // system, and return that foreign case's intake to the caller. Only an empty
  // POST body (which parses fine to `{}`) reaches the untargeted path.
  const parsed = targetSchema.safeParse(
    req.method === "POST" ? await req.json().catch(() => ({})) : {}
  );
  if (!parsed.success) {
    return NextResponse.json({ error: "בקשה לא תקינה" }, { status: 400 });
  }
  const caseId = parsed.data.caseId;

  let profileId: string | null = null;
  try {
    await resetStaleClaims(new Date());

    const profile = await prisma.conversionProfile.findFirst({
      where: {
        storyTranscriptionStatus: "COMPLETED",
        storyTranscript: { not: null },
        ...CLAIMABLE,
        ...(caseId ? { caseId } : {}),
      },
      select: { id: true, caseId: true, storyTranscript: true },
      orderBy: { updatedAt: "asc" },
    });

    // A targeted run that matched nothing is a no-op, not a success.
    if (!profile) {
      return NextResponse.json(
        { error: "אין סיפור אישי הממתין לניתוח בתיק זה", code: "NOTHING_TO_EXTRACT" },
        { status: 409 }
      );
    }

    // The status is part of the WHERE, so this is an atomic claim: two
    // concurrent invocations can never both call Gemini for the same profile.
    // That is what makes exposing this on GET safe.
    const claimed = await prisma.conversionProfile.updateMany({
      where: { id: profile.id, ...CLAIMABLE },
      data: { intakeStatus: "PROCESSING" },
    });
    if (claimed.count !== 1) {
      return NextResponse.json(
        { error: "ניתוח כבר רץ על תיק זה", code: "INTAKE_IN_FLIGHT" },
        { status: 409 }
      );
    }
    profileId = profile.id;

    // No PII masking here on purpose: the raw audio of this same story already
    // went to Gemini for transcription, and masking would strip the very
    // entities (names, community, rabbi) the extraction exists to find.
    const ai = getGeminiClient();
    const completion = await ai.models.generateContent({
      model: STORY_INTAKE_MODEL,
      contents: [{ role: "user", parts: [{ text: buildStoryIntakePrompt(profile.storyTranscript!) }] }],
      config: {
        maxOutputTokens: STORY_INTAKE_MAX_OUTPUT_TOKENS,
        responseMimeType: "application/json",
      },
    });

    const intake = parseStoryIntake(completion.text);
    if (!intake.ok) {
      console.error("[ai/story-intake] unusable AI output", { profileId, reason: intake.reason });
      await releaseClaim(profileId);
      return NextResponse.json(
        { error: "ניתוח הסיפור האישי נכשל", reason: intake.reason },
        { status: 502 }
      );
    }

    const result = await runStoryIntake(
      { caseId: profile.caseId, intake: intake.data, now: new Date() },
      buildPorts(sessionUserId)
    );

    // Any failed branch makes this run non-terminal, so the row goes back to
    // FAILED (a claimable state) rather than staying latched. Two cases: the
    // save branch failed and the row is still PROCESSING, or save succeeded and
    // marked it COMPLETED while the manager escalation — the highest-severity
    // output here — was lost. Re-running is safe: the task dedupe and the fixed
    // manager-task title make every effect idempotent.
    if (result.failures.length > 0) await releaseClaim(profileId);

    // Both surfaces are server-rendered: the intake shows on the case page, the
    // gap follow-ups on the task list.
    revalidatePath(`/cases/${profile.caseId}`);
    revalidatePath("/tasks");

    // 207 when some branch failed — a partial fan-out is neither a success the
    // UI should report plainly nor an error that undoes what did land.
    return NextResponse.json(
      { intake: intake.data, result },
      { status: result.failures.length > 0 ? 207 : 200 }
    );
  } catch (err) {
    console.error("[ai/story-intake]", err);
    if (profileId) await releaseClaim(profileId);
    return NextResponse.json({ error: "ניתוח הסיפור האישי נכשל" }, { status: 500 });
  }
}

// GET so a future Vercel Cron entry needs no code change (its dispatcher
// defaults to GET); POST is the manual staff trigger. Both are safe on the same
// handler thanks to the atomic claim above.
export const GET = handle;
export const POST = handle;
