import type { DefaultSession } from "next-auth"
// @ts-ignore – generated by postinstall / npm run db:generate
import type { UserRole } from "@/generated/prisma/client"

declare module "next-auth" {
  interface User {
    role: UserRole
  }

  interface Session {
    user: {
      id:   string
      role: UserRole
    } & DefaultSession["user"]
  }
}

declare module "next-auth/jwt" {
  interface JWT {
    id:   string
    role: UserRole
  }
}
