import type { DefaultSession } from "next-auth"
// @ts-ignore – generated by postinstall / npm run db:generate
import type { UserRole, UserStatus } from "@/generated/prisma/client"

declare module "next-auth" {
  interface User {
    role: UserRole
    status: UserStatus
  }

  interface Session {
    user: {
      id:     string
      role:   UserRole
      status: UserStatus
    } & DefaultSession["user"]
  }
}

declare module "next-auth/jwt" {
  interface JWT {
    id:     string
    role:   UserRole
    status: UserStatus
    // Epoch ms of the last DB status re-check; drives the throttled revocation
    // window in auth.ts's jwt callback.
    statusCheckedAt: number
  }
}
