// Weekly health audit: scans the live case load for the three things that
// silently rot in a caseload — work that stopped moving, clients who went quiet
// on a document request, and whether the team is actually shipping steps.
//
//   npm run db:audit
//
// Read-only by design: this tool never writes. It is safe to run against
// production at any time, and safe to wire into a cron/Slack post later.
import "dotenv/config";
import {
  PrismaClient,
  CaseStatus,
  CaseStep,
  DocumentStatus,
  // @ts-ignore – generated by npm run db:generate
} from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { CASE_STATUS_LABELS } from "../src/lib/constants";

// Prisma 7: the driver adapter owns the connection. CLI/seed use DIRECT_URL.
const adapter = new PrismaPg(process.env.DIRECT_URL ?? process.env.DATABASE_URL!);
// @ts-ignore – constructor accepts adapter in Prisma 7
const prisma = new PrismaClient({ adapter });

const BASE_URL = "http://localhost:3000";

const VELOCITY_WINDOW_DAYS = 7;
const FROZEN_AFTER_DAYS = 14;
const BLOCKED_AFTER_DAYS = 5;

const DAY_MS = 24 * 60 * 60 * 1000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS);
const daysSince = (d: Date) => Math.floor((Date.now() - d.getTime()) / DAY_MS);

// A case's real "last touched" moment. CaseActivity is the intent-bearing feed,
// but it only starts at CASE_CREATED — rows written before the timeline shipped
// have none, and `updatedAt` moves on any field write. Preferring the activity
// feed and falling back to updatedAt means a case is never reported as frozen
// just because it predates the timeline.
type CaseRow = {
  id: string;
  caseNumber: string;
  status: CaseStatus;
  updatedAt: Date;
  client: { fullName: string };
  activities: { createdAt: Date }[];
};
const lastTouched = (c: CaseRow): Date => c.activities[0]?.createdAt ?? c.updatedAt;

// ─── Report formatting ────────────────────────────────────────────────────────

// Hebrew is RTL but case numbers, day counts and URLs are LTR. Mixing them on
// one line lets the terminal's bidi algorithm reorder the visible text, so URLs
// get their own line and numbers are kept away from line edges.
const RULE = "─".repeat(52);

// Hebrew has no "1 items" form — a bare numeral in front of a plural noun reads
// as broken copy. This report goes to the office director, so the singular case
// gets its own wording rather than a numeral.
const plural = (n: number, one: string, many: string) => (n === 1 ? one : `${n} ${many}`);

function heading(icon: string, title: string, subtitle: string): string {
  return `\n${icon}  ${title}\n   ${subtitle}\n${RULE}`;
}

function caseLine(c: CaseRow, idleDays: number, note: string): string {
  const status = CASE_STATUS_LABELS[c.status] ?? c.status;
  return [
    `   • ${c.client.fullName} — ${c.caseNumber}`,
    `     ${status} · ${note} (${plural(idleDays, "יום אחד", "ימים")})`,
    `     ${BASE_URL}/cases/${c.id}`,
  ].join("\n");
}

function section(icon: string, title: string, subtitle: string, lines: string[], emptyNote: string): string {
  const body = lines.length ? lines.join("\n\n") : `   ${emptyNote}`;
  return `${heading(icon, title, subtitle)}\n${body}`;
}

// ─── Metrics ──────────────────────────────────────────────────────────────────

// Steps only ever move forward through the journey, so counting STEP_CHANGED is
// a count of real progress — not of edits, uploads or staff chatter.
async function weeklyVelocity(): Promise<number> {
  return prisma.caseActivity.count({
    where: { type: "STEP_CHANGED", createdAt: { gte: daysAgo(VELOCITY_WINDOW_DAYS) } },
  });
}

// Closed cases are excluded: a closed case is *supposed* to be inactive, and
// including them would bury the live ones under permanent noise. Everything
// else — including APPROVED/REJECTED — stays in scope, because those still sit
// in PIPELINE_COLUMNS and can need an appeal or a follow-up.
async function frozenCases(): Promise<{ row: CaseRow; idleDays: number }[]> {
  const rows: CaseRow[] = await prisma.case.findMany({
    where: { status: { not: CaseStatus.CLOSED } },
    select: {
      id: true,
      caseNumber: true,
      status: true,
      updatedAt: true,
      client: { select: { fullName: true } },
      activities: { select: { createdAt: true }, orderBy: { createdAt: "desc" }, take: 1 },
    },
  });

  return rows
    .map((row) => ({ row, idleDays: daysSince(lastTouched(row)) }))
    .filter(({ idleDays }) => idleDays >= FROZEN_AFTER_DAYS)
    .sort((a, b) => b.idleDays - a.idleDays);
}

// The client's move, not ours: the journey is parked on the upload screen with
// at least one document still missing or bounced back, and nothing has happened
// since. Distinct from "frozen" — this needs a nudge to the client, not to the
// agent — so a long-idle case legitimately appears in both lists.
async function blockedOnClient(): Promise<{ row: CaseRow; idleDays: number; missing: number; rejected: number }[]> {
  const rows = await prisma.case.findMany({
    where: {
      status: { not: CaseStatus.CLOSED },
      portalStep: CaseStep.PENDING_DOCS,
      checklist: { some: { status: { in: [DocumentStatus.MISSING, DocumentStatus.REJECTED] } } },
    },
    select: {
      id: true,
      caseNumber: true,
      status: true,
      updatedAt: true,
      client: { select: { fullName: true } },
      activities: { select: { createdAt: true }, orderBy: { createdAt: "desc" }, take: 1 },
      checklist: {
        where: { status: { in: [DocumentStatus.MISSING, DocumentStatus.REJECTED] } },
        select: { status: true },
      },
    },
  });

  return rows
    .map((row) => ({
      row,
      idleDays: daysSince(lastTouched(row)),
      missing: row.checklist.filter((i: { status: DocumentStatus }) => i.status === DocumentStatus.MISSING).length,
      rejected: row.checklist.filter((i: { status: DocumentStatus }) => i.status === DocumentStatus.REJECTED).length,
    }))
    .filter(({ idleDays }) => idleDays >= BLOCKED_AFTER_DAYS)
    .sort((a, b) => b.idleDays - a.idleDays);
}

// ─── Report ───────────────────────────────────────────────────────────────────

async function main() {
  const [velocity, frozen, blocked] = await Promise.all([weeklyVelocity(), frozenCases(), blockedOnClient()]);

  const today = new Date().toLocaleDateString("he-IL");
  const out: string[] = [
    RULE,
    `📊  דוח בריאות שבועי — SmartCase`,
    `    ${today}`,
    RULE,
  ];

  out.push(
    heading("⚡", "תפוקת הצוות", `מעברי שלב ב-${VELOCITY_WINDOW_DAYS} הימים האחרונים`),
    velocity > 0 ? `   ${plural(velocity, "מעבר שלב אחד", "מעברי שלב")}` : `   אין מעברי שלב בשבוע האחרון`,
  );

  out.push(
    section(
      "🧊",
      "תיקים קפואים",
      `ללא פעילות מעל ${FROZEN_AFTER_DAYS} ימים`,
      frozen.map(({ row, idleDays }) => caseLine(row, idleDays, "ללא פעילות")),
      "אין תיקים קפואים 🎉",
    ),
  );

  out.push(
    section(
      "⏳",
      "ממתין ללקוח",
      `תקועים בהעלאת מסמכים מעל ${BLOCKED_AFTER_DAYS} ימים`,
      blocked.map(({ row, idleDays, missing, rejected }) => {
        const parts = [
          missing > 0 ? plural(missing, "מסמך אחד חסר", "מסמכים חסרים") : null,
          rejected > 0 ? plural(rejected, "מסמך אחד נדחה", "מסמכים נדחו") : null,
        ]
          .filter(Boolean)
          .join(" · ");
        return caseLine(row, idleDays, parts);
      }),
      "אין תיקים תקועים אצל לקוחות 🎉",
    ),
  );

  out.push(`\n${RULE}`);
  console.log(out.join("\n"));
}

main()
  .catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
