// Local dev tool: provisions a complete, portal-ready CONVERSION test case in one
// command — client, case, share token, checklist and an initialized timeline —
// then prints the two URLs needed to drive it from both sides.
//
// Everything reachable from the printed links is produced the same way the real
// app produces it: the same 256-bit token recipe as `generatePortalLink`, the
// same checklist templates `createCase` reads, and the same `logCaseActivity`
// writer the Server Actions and public routes share. A case seeded here is
// indistinguishable from one opened through the UI.
//
//   npm run db:seed-test -- --name="Moti Test" --step="PENDING_DOCS"
//
// stdout is JSON and nothing else, so it pipes into jq:
//   npm run db:seed-test --silent -- --name=X | jq -r .publicUrl
import "dotenv/config";
import { randomBytes, randomInt } from "node:crypto";
import {
  PrismaClient,
  CaseStep,
  CaseType,
  CaseStatus,
  Priority,
  DocumentStatus,
  Gender,
  UserRole,
  UserStatus,
  // @ts-ignore – generated by npm run db:generate
} from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { logCaseActivity } from "../src/lib/activity";

// Prisma 7: the driver adapter owns the connection. CLI/seed use DIRECT_URL.
const adapter = new PrismaPg(process.env.DIRECT_URL ?? process.env.DATABASE_URL!);
// @ts-ignore – constructor accepts adapter in Prisma 7
const prisma = new PrismaClient({ adapter });

// The tool exists to drive `next dev`, so the links are always local — unlike
// the notification mailer, which reads NEXT_PUBLIC_APP_URL to reach production.
const BASE_URL = "http://localhost:3000";
// Mirrors PORTAL_TOKEN_TTL_DAYS in src/lib/actions.ts.
const TOKEN_TTL_DAYS = 30;
// Overridable so a real inbox can receive the Slice 6 rejection mail; the
// default is an RFC 2606 address that can never deliver by accident.
const TEST_EMAIL = process.env.TEST_CLIENT_EMAIL || "smartcase.test@example.com";

// Accepts both `--flag value` and `--flag=value`.
function parseFlags(argv: string[]): Record<string, string> {
  const flags: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith("--")) continue;
    const eq = arg.indexOf("=");
    if (eq !== -1) {
      flags[arg.slice(2, eq)] = arg.slice(eq + 1);
    } else {
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) throw new Error(`Flag ${arg} expects a value`);
      flags[arg.slice(2)] = next;
      i++;
    }
  }
  return flags;
}

// nationalId is @unique and every run mints a fresh client, so a collision would
// abort the run — cheap to just re-roll.
async function uniqueNationalId(): Promise<string> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const id = String(randomInt(100_000_000, 1_000_000_000));
    const taken = await prisma.client.findUnique({ where: { nationalId: id }, select: { id: true } });
    if (!taken) return id;
  }
  throw new Error("Could not allocate a unique nationalId after 5 attempts");
}

// Same sequence the UI allocates from, so seeded cases sort naturally alongside
// real ones in the dashboard.
async function nextCaseNumber(): Promise<string> {
  const prefix = `SC-${new Date().getFullYear()}-`;
  const last = await prisma.case.findFirst({
    where: { caseNumber: { startsWith: prefix } },
    orderBy: { caseNumber: "desc" },
    select: { caseNumber: true },
  });
  const lastSeq = last ? parseInt(last.caseNumber.slice(prefix.length), 10) || 0 : 0;
  return `${prefix}${String(lastSeq + 1).padStart(5, "0")}`;
}

async function main() {
  const flags = parseFlags(process.argv.slice(2));

  const name = flags.name?.trim();
  if (!name) throw new Error('Missing --name (e.g. --name="Moti Test")');

  const step = (flags.step ?? CaseStep.WELCOME) as CaseStep;
  if (!Object.values(CaseStep).includes(step)) {
    throw new Error(`Invalid --step "${step}". Expected one of: ${Object.values(CaseStep).join(", ")}`);
  }

  // Cases require a creator FK; the portal journey belongs to a real staff owner.
  const creator = await prisma.user.findFirst({
    where: { role: UserRole.ADMIN, status: UserStatus.APPROVED },
    select: { id: true },
  });
  if (!creator) throw new Error("No approved ADMIN user found — run `npm run db:seed` first");

  const templates = await prisma.documentChecklistTemplate.findMany({
    where: { caseType: CaseType.CONVERSION },
    select: { id: true },
  });
  if (templates.length === 0) {
    throw new Error("No CONVERSION checklist templates found — run `npm run db:seed` first");
  }

  const nationalId = await uniqueNationalId();
  const caseNumber = await nextCaseNumber();
  // Identical recipe to generatePortalLink: a 256-bit bearer secret stored raw.
  const token = randomBytes(32).toString("base64url");

  // One transaction: a failure anywhere leaves no half-built case and no orphan
  // timeline entry, which is exactly why logCaseActivity takes the tx client.
  const created = await prisma.$transaction(async (tx) => {
    const client = await tx.client.create({
      data: {
        fullName: name,
        nationalId,
        dateOfBirth: new Date("1990-01-01"),
        gender: Gender.OTHER,
        phone: "050-0000000",
        email: TEST_EMAIL,
      },
      select: { id: true },
    });

    const c = await tx.case.create({
      data: {
        caseNumber,
        clientId: client.id,
        createdById: creator.id,
        caseType: CaseType.CONVERSION,
        status: CaseStatus.NEW_INTAKE,
        priority: Priority.MEDIUM,
        portalStep: step,
        clientPortalToken: token,
        clientPortalTokenExpiresAt: new Date(Date.now() + TOKEN_TTL_DAYS * 24 * 60 * 60 * 1000),
        hasMissingDocuments: true,
        statusHistory: {
          create: { changedById: creator.id, previousStatus: null, newStatus: CaseStatus.NEW_INTAKE },
        },
        checklist: {
          create: templates.map((t: { id: string }) => ({ templateId: t.id, status: DocumentStatus.MISSING })),
        },
      },
      select: { id: true },
    });

    await logCaseActivity(
      tx,
      c.id,
      "CASE_CREATED",
      `התיק נפתח: ${caseNumber}`,
      { caseType: CaseType.CONVERSION, priority: Priority.MEDIUM, source: "cli:create-test-case" },
      creator.id,
    );

    return c;
  });

  console.log(
    JSON.stringify(
      {
        caseId: created.id,
        portalToken: token,
        staffUrl: `${BASE_URL}/cases/${created.id}`,
        publicUrl: `${BASE_URL}/share/conversion/${token}`,
      },
      null,
      2,
    ),
  );
}

main()
  .catch((e) => {
    // stderr keeps stdout parseable as JSON even on failure.
    console.error(e instanceof Error ? e.message : e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
