// Email + password gate shared by NextAuth's Credentials `authorize()` and the
// mobile login route (POST /api/auth/login). One implementation so the two
// entry points can never drift on the enumeration rule: the password is
// verified BEFORE account state is revealed, and an unknown email and a wrong
// password are indistinguishable ("invalid").
import bcrypt from "bcryptjs"
// @ts-ignore – generated by postinstall / npm run db:generate
import type { UserRole, UserStatus } from "@/generated/prisma/client"
import { prisma } from "@/lib/prisma"

export type AuthenticatedUser = {
  id: string
  name: string | null
  email: string
  role: UserRole
  status: UserStatus
}

export type CredentialsOutcome =
  | { ok: true; user: AuthenticatedUser }
  | { ok: false; reason: "invalid" | "pending_approval" | "suspended" }

export async function verifyCredentials(email: string, password: string): Promise<CredentialsOutcome> {
  // Case-insensitive: emails are stored as-entered at registration, so
  // "Foo@x.com" must still resolve the existing "foo@x.com" account.
  const user = await prisma.user.findFirst({
    where: { email: { equals: email, mode: "insensitive" } },
    select: { id: true, name: true, email: true, passwordHash: true, role: true, status: true },
  })
  if (!user) return { ok: false, reason: "invalid" }

  const valid = await bcrypt.compare(password, user.passwordHash)
  if (!valid) return { ok: false, reason: "invalid" }

  if (user.status === "PENDING_APPROVAL") return { ok: false, reason: "pending_approval" }
  if (user.status === "SUSPENDED") return { ok: false, reason: "suspended" }

  return { ok: true, user: { id: user.id, name: user.name, email: user.email, role: user.role, status: user.status } }
}

// Fixed-window attempt counter for the login route (per client IP). In-memory:
// bounds a single serverless instance's throughput, which is the credential-
// stuffing surface that matters here; it is not a cross-instance guarantee.
export const LOGIN_RATE_LIMIT_PER_MINUTE = 10
const WINDOW_MS = 60_000
const attempts = new Map<string, { count: number; windowStart: number }>()

export function checkLoginRate(key: string, now = Date.now()): boolean {
  const entry = attempts.get(key)
  if (!entry || now - entry.windowStart >= WINDOW_MS) {
    attempts.set(key, { count: 1, windowStart: now })
    return true
  }
  entry.count += 1
  return entry.count <= LOGIN_RATE_LIMIT_PER_MINUTE
}
